const $=id=>document.getElementById(id),GLYPH={html:'🌐',css:'🎨',js:'⚡',json:'🧩',svg:'◈',md:'📝',img:'🖼️',dir:'🗂️'};
let ROOT,current,view='grid',currentFile=null,tabs=[],pins=[],changes={},undoStack=[],editing=false,missionStart=Date.now();
const STORE='fileverse-pro-v3',missions=[['folder','Open a folder'],['pin','Pin a file'],['edit','Edit and save code'],['create','Create a file'],['run','Run live preview']];
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function hi(s){return esc(s).replace(/\b(const|let|function|return|if|else|await|class|import|export|new)\b/g,'<span class="k">$1</span>').replace(/(&lt;\/?[\w-]+)/g,'<span class="c">$1</span>').replace(/(".*?"|'.*?')/g,'<span class="a">$1</span>')}
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function log(m){const p=document.createElement('p');p.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' · '+m;$('timeline').prepend(p)}
function badge(n){document.querySelector(`[data-badge="${n}"]`)?.classList.add('unlocked')}
function pathOf(n){const a=[];for(let x=n;x&&x.parent;x=x.parent)a.unshift(x.name);return '/'+a.join('/')}
function link(n,p=null){n.parent=p;(n.children||[]).forEach(c=>link(c,n))}
function files(n=ROOT,a=[]){(n.children||[]).forEach(c=>c.type==='dir'?files(c,a):a.push(c));return a}
function dirs(n=ROOT,a=[]){(n.children||[]).forEach(c=>{if(c.type==='dir'){a.push(c);dirs(c,a)}});return a}
function snapshot(){return JSON.stringify(ROOT,(k,v)=>k==='parent'?undefined:v)}
function pushUndo(label){undoStack.push({label,data:snapshot()});if(undoStack.length>15)undoStack.shift()}
function persist(){localStorage.setItem(STORE,JSON.stringify({root:JSON.parse(snapshot()),view,pins:pins.map(pathOf),tabs:tabs.map(pathOf),changes,theme:document.body.className,missions:Object.fromEntries(missions.map(m=>[m[0],document.querySelector(`[data-mission="${m[0]}"]`)?.classList.contains('done')]))}));$('saveStatus').textContent='Saved locally'}
function findPath(path){return [...files(),...dirs(),ROOT].find(x=>pathOf(x)===path)}
function restorePins(paths=[]){pins=paths.map(findPath).filter(Boolean)}
function complete(id){document.querySelector(`[data-mission="${id}"]`)?.classList.add('done');const done=document.querySelectorAll('.mission.done').length;$('missionScore').textContent=`${done}/5`;if(done===5){badge('master');toast('🏆 FileVerse Master unlocked!')}persist()}
function renderMissions(saved={}){$('missions').innerHTML=missions.map(([id,t],i)=>`<article class="mission ${saved[id]?'done':''}" data-mission="${id}"><b>${i+1}</b><span>${t}</span><em>✓</em></article>`).join('');complete('__none__')}
setInterval(()=>{const s=Math.floor((Date.now()-missionStart)/1000);$('missionTime').textContent=String(s/60|0).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},1000);
function renderTree(n=ROOT){const wrap=document.createElement('div');(n.children||[]).forEach(f=>{const row=document.createElement('div');row.className='node';row.draggable=true;row.innerHTML=`<span class="tw">${f.type==='dir'?'▶':''}</span><span class="ic">${GLYPH[f.type]||'📄'}</span><span class="nm">${f.name}</span>${f.type==='dir'?`<span class="count">${f.children.length}</span>`:''}`;row.onclick=()=>f.type==='dir'?openDir(f):openFile(f);row.oncontextmenu=e=>showContext(e,f);row.ondragstart=e=>e.dataTransfer.setData('text/path',pathOf(f));if(f.type==='dir'){row.ondragover=e=>{e.preventDefault();row.classList.add('drop')};row.ondragleave=()=>row.classList.remove('drop');row.ondrop=e=>{e.preventDefault();row.classList.remove('drop');moveNode(e.dataTransfer.getData('text/path'),f)};const kids=renderTree(f);kids.className='children';wrap.append(row,kids)}else wrap.append(row)});return wrap}
function rebuildTree(){$('tree').innerHTML='';$('tree').append(renderTree());renderPins();renderChanges()}
function openDir(d){current=d;complete('folder');$('dirTitle').textContent=d===ROOT?'Root':d.name;const chain=[];for(let n=d;n;n=n.parent)chain.unshift(n);$('crumbs').innerHTML='';chain.forEach((n,i)=>{if(i)$('crumbs').append('/');const b=document.createElement('button');b.textContent=n===ROOT?'~':n.name;b.onclick=()=>openDir(n);$('crumbs').append(b)});renderItems(d.children||[]);updateStatus()}
function renderItems(items){$('grid').innerHTML='';items.forEach(f=>{const b=document.createElement('button');b.className='card';b.draggable=true;b.innerHTML=`<span class="tag">${f.type}</span><div class="glyph">${GLYPH[f.type]||'📄'}</div><div class="nm">${f.name}</div><div class="meta">${f.type==='dir'?(f.children||[]).length+' items':(f.size||calcSize(f.code))}</div>`;b.onclick=()=>f.type==='dir'?openDir(f):openFile(f);b.oncontextmenu=e=>showContext(e,f);b.ondragstart=e=>e.dataTransfer.setData('text/path',pathOf(f));$('grid').append(b)});$('emptyState').hidden=!!items.length;$('mFiles').textContent=items.filter(x=>x.type!=='dir').length;$('mFolders').textContent=items.filter(x=>x.type==='dir').length}
function updateStatus(){$('statusPath').textContent=$('branchSelect').value+' '+pathOf(current||ROOT);$('statusCount').textContent=(current?.children?.length||0)+' items';$('statusView').textContent=view==='grid'?'Grid mode':'List mode';$('mChanges').textContent=Object.keys(changes).length}
function calcSize(s=''){return Math.max(1,new Blob([s]).size/1024).toFixed(1)+' KB'}
function openFile(f){currentFile=f;if(!tabs.includes(f))tabs.push(f);renderTabs();$('pvIcon').textContent=GLYPH[f.type]||'📄';$('pvName').textContent=f.name;$('pvPath').textContent=pathOf(f);$('pvType').textContent=f.type.toUpperCase();$('pvSize').textContent=calcSize(f.code);$('pvLines').textContent=(f.code||'').split('\n').length;$('pvMod').textContent=changes[pathOf(f)]||'clean';$('pinBtn').textContent=pins.includes(f)?'★':'☆';showCode();$('drawer').classList.add('show');$('scrim').classList.add('show');badge('explorer');log('Opened '+f.name)}
function showCode(){editing=false;$('codeInput').hidden=true;$('pvCode').hidden=false;$('pvCode').innerHTML=hi(currentFile?.code||'');renderLines();renderMiniMap()}
function editCode(){if(!currentFile)return;editing=true;$('codeInput').hidden=false;$('pvCode').hidden=true;$('codeInput').value=currentFile.code||'';$('codeInput').focus();badge('editor')}
function saveCode(){if(!currentFile||!editing)return;pushUndo('Edit '+currentFile.name);currentFile.code=$('codeInput').value;mark(currentFile,'M');complete('edit');showCode();persist();toast('File saved')}
function renderLines(){const n=(currentFile?.code||'').split('\n').length;$('lineNumbers').innerHTML=Array.from({length:n},(_,i)=>`<span>${i+1}</span>`).join('')}
function renderMiniMap(){$('miniMap').innerHTML=(currentFile?.code||'').split('\n').slice(0,80).map(l=>`<i style="width:${Math.min(100,8+l.length)}%"></i>`).join('')}
function renderTabs(){$('tabs').innerHTML='';tabs.forEach(f=>{const b=document.createElement('button');b.className=f===currentFile?'active':'';b.textContent=f.name+' ×';b.onclick=e=>{if(e.offsetX>b.clientWidth-24){tabs=tabs.filter(x=>x!==f);renderTabs()}else openFile(f)};$('tabs').append(b)})}
function renderPins(){$('pinnedList').innerHTML='';(pins.length?pins:[{name:'No pins yet',empty:true}]).forEach(f=>{const b=document.createElement('button');b.textContent=f.empty?f.name:'★ '+f.name;if(!f.empty)b.onclick=()=>openFile(f);$('pinnedList').append(b)})}
function mark(f,status){changes[pathOf(f)]=status;renderChanges();updateStatus();persist()}
function renderChanges(){$('changesList').innerHTML='';const list=Object.entries(changes);$('changesList').innerHTML=list.length?list.map(([p,s])=>`<button data-path="${p}"><b>${s}</b><span>${p}</span></button>`).join(''):'<p class="muted">Working tree clean</p>';$('changesList').querySelectorAll('button').forEach(b=>b.onclick=()=>{const f=findPath(b.dataset.path);if(f)openFile(f)})}
function newItem(){showModal('New file or folder',`<label>Name<input id="newName" placeholder="components/card.js"></label><label>Type<select id="newType"><option>js</option><option>html</option><option>css</option><option>json</option><option>md</option><option>svg</option><option value="dir">folder</option></select></label><button id="createItem">Create</button>`,()=>{$('createItem').onclick=()=>{const name=$('newName').value.trim();if(!name)return;pushUndo('Create '+name);const type=$('newType').value,node={name,type,code:type==='dir'?undefined:template(type,name),children:type==='dir'?[]:undefined};(current||ROOT).children.push(node);link(ROOT);mark(node,'A');complete('create');badge('creator');hideModal();rebuildTree();openDir(current||ROOT);toast('Created '+name)}})}
function template(t,n){return t==='html'?`<!DOCTYPE html>\n<html><body><h1>${n}</h1></body></html>`:t==='css'?':root {\n  --accent: #53f4ff;\n}':t==='js'?`console.log('${n} ready');`:t==='json'?'{\n  "ready": true\n}':t==='md'?`# ${n}`:'<svg viewBox="0 0 100 100"></svg>'}
function showContext(e,f){e.preventDefault();const m=$('contextMenu');m.innerHTML=['Open','Rename','Duplicate','Pin / unpin','Copy path','Download','Delete'].map(x=>`<button>${x}</button>`).join('');m.style.left=e.clientX+'px';m.style.top=e.clientY+'px';m.hidden=false;const [op,re,du,pi,cp,dl,de]=m.children;op.onclick=()=>f.type==='dir'?openDir(f):openFile(f);re.onclick=()=>renameNode(f);du.onclick=()=>duplicateNode(f);pi.onclick=()=>togglePin(f);cp.onclick=()=>navigator.clipboard.writeText(pathOf(f));dl.onclick=()=>downloadFile(f);de.onclick=()=>deleteNode(f)}
document.addEventListener('click',e=>{if(!e.target.closest('#contextMenu'))$('contextMenu').hidden=true});
function renameNode(f){showModal('Rename',`<label>New name<input id="renameInput" value="${f.name}"></label><button id="renameSave">Rename</button>`,()=>{$('renameSave').onclick=()=>{pushUndo('Rename '+f.name);const old=pathOf(f);f.name=$('renameInput').value.trim()||f.name;changes[old]='D';mark(f,'A');hideModal();rebuildTree();openDir(f.parent);toast('Renamed')}})}
function duplicateNode(f){pushUndo('Duplicate '+f.name);const copy=JSON.parse(JSON.stringify(f,(k,v)=>k==='parent'?undefined:v));copy.name=f.name.replace(/(\.[^.]+)?$/, '-copy$1');f.parent.children.push(copy);link(ROOT);mark(copy,'A');rebuildTree();openDir(f.parent)}
function deleteNode(f){if(!confirm('Delete '+f.name+'?'))return;pushUndo('Delete '+f.name);f.parent.children=f.parent.children.filter(x=>x!==f);changes[pathOf(f)]='D';tabs=tabs.filter(x=>x!==f);pins=pins.filter(x=>x!==f);rebuildTree();openDir(f.parent);persist()}
function togglePin(f){if(!f||f.type==='dir')return;pins=pins.includes(f)?pins.filter(x=>x!==f):[...pins,f];complete('pin');renderPins();persist()}
function moveNode(from,target){const f=findPath(from);if(!f||f===target||f.parent===target)return;pushUndo('Move '+f.name);f.parent.children=f.parent.children.filter(x=>x!==f);target.children.push(f);link(ROOT);mark(f,'M');rebuildTree();openDir(target);toast('Moved '+f.name)}
function undo(){const u=undoStack.pop();if(!u)return toast('Nothing to undo');ROOT=JSON.parse(u.data);link(ROOT);current=ROOT;changes={};rebuildTree();openDir(ROOT);persist();toast('Undid: '+u.label)}
function buildPreview(){const html=files().find(f=>f.name==='index.html')?.code||'<main id="app"></main>',css=files().filter(f=>f.type==='css').map(f=>f.code).join('\n'),js=files().filter(f=>f.type==='js').map(f=>f.code).join('\n');return html.replace('</head>',`<style>${css}</style></head>`).replace('</body>',`<script>${js.replace(/<\/script>/g,'<\\/script>')}<\/script></body>`)}
function runPreview(){$('liveFrame').srcdoc=buildPreview();$('livePanel').classList.add('show');complete('run');log('Live preview compiled');toast('Project running')}
function graph(){const links=[['index.html','style.css'],['index.html','extras.css'],['index.html','script.js'],['script.js','data.json']];$('graph').innerHTML=links.map(([a,b])=>`<div class="edge"><span>${a}</span><i>→</i><span>${b}</span></div>`).join('');$('graphPanel').hidden=false}
function search(){let q=$('searchInput').value,type=$('typeFilter').value,cs=$('caseSearch').checked,word=$('wordSearch').checked,rx=$('regexSearch').checked;if(!q&&!type)return openDir(current||ROOT);const flags=cs?'':'i';let re;try{re=rx?new RegExp(q,flags):new RegExp(word?'\\b'+q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b':q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),flags)}catch{return toast('Invalid regex')};const out=files().filter(f=>(!type||f.type===type)&&re.test(f.name+'\n'+(f.code||'')));$('dirTitle').textContent='Search results';renderItems(out)}
function runTerminal(c){if(c==='clear')return $('terminalLog').innerHTML='';const out=c==='git status'?Object.keys(changes).length?Object.entries(changes).map(([p,s])=>`${s} ${p}`):['Working tree clean']:c==='deploy pages'?['Building…','Deployed to GitHub Pages.']:['Compiling modules…','Ready.'];$('terminalLog').innerHTML+=`<p><span>$</span> ${c}</p>`+out.map(x=>`<p>${x}</p>`).join('');if(c==='deploy pages')badge('publisher')}
function showModal(title,html,ready){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').hidden=false;ready?.()}
function hideModal(){$('modal').hidden=true}
function downloadFile(f){if(!f||f.type==='dir')return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([f.code||'']));a.download=f.name;a.click();URL.revokeObjectURL(a.href)}
function exportProject(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([snapshot()],{type:'application/json'}));a.download='fileverse-project.json';a.click();URL.revokeObjectURL(a.href)}
function commit(){if(!Object.keys(changes).length)return toast('Nothing to commit');showModal('Commit changes','<label>Message<input id="commitMessage" value="Upgrade FileVerse workspace"></label><button id="commitSave">Commit</button>',()=>{$('commitSave').onclick=()=>{log('Commit: '+$('commitMessage').value);changes={};renderChanges();updateStatus();hideModal();persist();toast('Changes committed')}})}
function palette(){const cmds=[['New file',newItem],['Run project',runPreview],['Dependencies',graph],['Switch grid',()=>setView('grid')],['Switch list',()=>setView('list')],['Commit changes',commit],['Export project',exportProject]];$('palette').hidden=false;const render=q=>{$('paletteList').innerHTML='';cmds.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())).forEach(([n,fn])=>{const b=document.createElement('button');b.textContent=n;b.onclick=()=>{$('palette').hidden=true;fn()};$('paletteList').append(b)})};render('');$('paletteInput').value='';$('paletteInput').oninput=e=>render(e.target.value);$('paletteInput').focus()}
function setView(v){view=v;$('grid').className='grid'+(v==='list'?' list':'');$('btnGrid').classList.toggle('on',v==='grid');$('btnList').classList.toggle('on',v==='list');updateStatus();persist()}
function bind(){$('newBtn').onclick=newItem;$('runBtn').onclick=runPreview;$('undoBtn').onclick=undo;$('editBtn').onclick=editCode;$('saveBtn').onclick=saveCode;$('resetBtn').onclick=()=>{if(currentFile){$('codeInput').value=currentFile.original||currentFile.code;editCode()}};$('copyBtn').onclick=()=>navigator.clipboard.writeText(currentFile?.code||'');$('downloadBtn').onclick=()=>downloadFile(currentFile);$('pinBtn').onclick=()=>togglePin(currentFile);$('pvClose').onclick=()=>{$('drawer').classList.remove('show');$('scrim').classList.remove('show')};$('scrim').onclick=$('pvClose').onclick;$('shuffleBtn').onclick=()=>openFile(files()[Math.random()*files().length|0]);$('graphBtn').onclick=graph;$('closeGraph').onclick=()=>$('graphPanel').hidden=true;$('closePreview').onclick=()=>$('livePanel').classList.remove('show');$('refreshPreview').onclick=runPreview;$('exportBtn').onclick=exportProject;$('commitBtn').onclick=commit;$('modalClose').onclick=hideModal;$('btnGrid').onclick=()=>setView('grid');$('btnList').onclick=()=>setView('list');$('cmdBtn').onclick=palette;$('contrastBtn').onclick=()=>document.body.classList.toggle('high-contrast');$('motionBtn').onclick=()=>document.body.classList.toggle('reduce-motion');document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{document.body.className=b.dataset.theme==='neon'?'':'theme-'+b.dataset.theme;persist()});document.querySelectorAll('.terminal-actions button').forEach(b=>b.onclick=()=>runTerminal(b.dataset.cmd));['searchInput','typeFilter','caseSearch','wordSearch','regexSearch'].forEach(id=>$(id).addEventListener(id==='searchInput'?'input':'change',search));$('wrapBtn').onchange=e=>$('codeInput').classList.toggle('wrap',e.target.checked);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveCode()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();palette()}if(e.key==='Escape'){hideModal();$('palette').hidden=true}})}
async function init(){let data=await fetch('./data.json').then(r=>r.json());const saved=JSON.parse(localStorage.getItem(STORE)||'null');ROOT=saved?.root||data;link(ROOT);files().forEach(f=>f.original=f.original||f.code);current=ROOT;view=saved?.view||'grid';changes=saved?.changes||{};renderMissions(saved?.missions||{});rebuildTree();restorePins(saved?.pins);renderPins();openDir(ROOT);setView(view);if(saved?.theme)document.body.className=saved.theme;bind();setTimeout(()=>$('loader').classList.add('is-done'),700);log('Workspace booted')}
init();