(()=>{
const U=id=>document.getElementById(id);
const state={active:'split',left:null,right:null,console:[],commits:JSON.parse(localStorage.getItem('fileverse-ultra-commits')||'[]'),tour:0};
const safe=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function ready(fn){const tick=()=>window.ROOT&&typeof files==='function'?fn():setTimeout(tick,120);tick()}
function inject(){
 const deck=document.querySelector('.control-deck>div:first-child .mini-actions');
 const launch=document.createElement('button');launch.id='ultraLaunch';launch.className='ultra-launch';launch.textContent='✦ Ultra Studio';deck.append(launch);
 const panel=document.createElement('section');panel.id='ultraPanel';panel.className='ultra-panel';panel.innerHTML=`
 <div class="ultra-head"><div><p class="eyebrow">FileVerse Ultra</p><h2>Professional workspace tools</h2></div><div class="ultra-actions"><button id="importBtn">Import</button><button id="zipBtn">Export ZIP</button><button id="tourBtn">Product tour</button><input id="importInput" class="import-input" type="file" accept=".json,.zip"></div></div>
 <nav class="ultra-tabs" aria-label="Ultra tools">
  <button data-ultra="split" class="on">Split view</button><button data-ultra="console">Console</button><button data-ultra="device">Devices</button><button data-ultra="diff">Diff</button><button data-ultra="history">Git history</button><button data-ultra="templates">Templates</button><button data-ultra="audit">Audit</button><button data-ultra="ai">AI Assistant</button>
 </nav>
 <div id="uv-split" class="ultra-view on"></div><div id="uv-console" class="ultra-view"></div><div id="uv-device" class="ultra-view"></div><div id="uv-diff" class="ultra-view"></div><div id="uv-history" class="ultra-view"></div><div id="uv-templates" class="ultra-view"></div><div id="uv-audit" class="ultra-view"></div><div id="uv-ai" class="ultra-view"></div>`;
 document.querySelector('.workspace').after(panel);
 const tour=document.createElement('div');tour.id='tourOverlay';tour.className='tour-overlay';tour.innerHTML='<div id="tourCard" class="tour-card"><p class="eyebrow">Guided tour</p><h3 id="tourTitle"></h3><p id="tourText"></p><div class="tour-actions"><button id="tourPrev">Back</button><button id="tourNext">Next</button><button id="tourExit">Exit</button></div></div>';document.body.append(tour);
 bindUltra();renderAll();
}
function bindUltra(){
 U('ultraLaunch').onclick=()=>U('ultraPanel').scrollIntoView({behavior:'smooth'});
 document.querySelectorAll('[data-ultra]').forEach(b=>b.onclick=()=>switchView(b.dataset.ultra));
 U('zipBtn').onclick=exportZip;U('importBtn').onclick=()=>U('importInput').click();U('importInput').onchange=importProject;U('tourBtn').onclick=startTour;
 U('tourPrev').onclick=()=>tourStep(-1);U('tourNext').onclick=()=>tourStep(1);U('tourExit').onclick=endTour;
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='\\'){e.preventDefault();switchView('split');U('ultraPanel').scrollIntoView({behavior:'smooth'})}});
 const oldCommit=U('commitBtn').onclick;U('commitBtn').onclick=()=>{const before=Object.keys(changes||{}).length;oldCommit?.();if(before)addCommit('Workspace commit',before)};
 const oldRun=window.runPreview;window.runPreview=function(){oldRun();captureConsole();renderDevice()};
}
function switchView(name){state.active=name;document.querySelectorAll('[data-ultra]').forEach(b=>b.classList.toggle('on',b.dataset.ultra===name));document.querySelectorAll('.ultra-view').forEach(v=>v.classList.toggle('on',v.id==='uv-'+name));renderView(name)}
function renderAll(){['split','console','device','diff','history','templates','audit','ai'].forEach(renderView)}
function renderView(name){({split:renderSplit,console:renderConsole,device:renderDevice,diff:renderDiff,history:renderHistory,templates:renderTemplates,audit:renderAudit,ai:renderAI}[name]||(()=>{}))()}
function fileOptions(selected){return files().map(f=>`<option value="${safe(pathOf(f))}" ${f===selected?'selected':''}>${safe(pathOf(f))}</option>`).join('')}
function renderSplit(){const list=files();state.left=state.left&&files().includes(state.left)?state.left:list.find(f=>f.type==='html')||list[0];state.right=state.right&&files().includes(state.right)?state.right:list.find(f=>f.type==='css')||list[1]||list[0];U('uv-split').innerHTML=`<div class="ultra-actions"><button id="splitSwap">⇄ Swap</button><button id="splitSave">Save both</button><button id="splitFormat">Format active files</button><span class="kbd-hint">Ctrl/Cmd + \\ opens Split View</span></div><div class="split-editor"><section class="split-pane"><header><select id="splitLeftFile">${fileOptions(state.left)}</select></header><textarea id="splitLeftCode" spellcheck="false">${safe(state.left?.code||'')}</textarea></section><section class="split-pane"><header><select id="splitRightFile">${fileOptions(state.right)}</select></header><textarea id="splitRightCode" spellcheck="false">${safe(state.right?.code||'')}</textarea></section></div>`;
 U('splitLeftFile').onchange=e=>{state.left=findPath(e.target.value);renderSplit()};U('splitRightFile').onchange=e=>{state.right=findPath(e.target.value);renderSplit()};
 U('splitSave').onclick=saveSplit;U('splitSwap').onclick=()=>{[state.left,state.right]=[state.right,state.left];renderSplit()};U('splitFormat').onclick=()=>{U('splitLeftCode').value=formatCode(U('splitLeftCode').value,state.left.type);U('splitRightCode').value=formatCode(U('splitRightCode').value,state.right.type)};
}
function saveSplit(){[[state.left,U('splitLeftCode').value],[state.right,U('splitRightCode').value]].forEach(([f,c])=>{if(f&&f.code!==c){pushUndo('Split edit '+f.name);f.code=c;mark(f,'M')}});persist();rebuildTree();toast('Split files saved');renderDiff();renderAudit()}
function formatCode(code,type){if(type==='json'){try{return JSON.stringify(JSON.parse(code),null,2)}catch{return code}}if(type==='css')return code.replace(/\{/g,'{\n  ').replace(/;/g,';\n  ').replace(/\s*\}/g,'\n}').replace(/\n\s*\n/g,'\n');if(type==='html')return code.replace(/></g,'>\n<');return code.replace(/;(?=\S)/g,';\n')}
function captureConsole(){state.console=[{t:'ok',m:'Project compiled successfully'},{t:'ok',m:`${files().length} files loaded`}];files().forEach(f=>{if(f.type==='js'){try{new Function(f.code||'')}catch(e){state.console.push({t:'error',m:`${f.name}: ${e.message}`})}}if(f.type==='json'){try{JSON.parse(f.code||'{}')}catch(e){state.console.push({t:'error',m:`${f.name}: invalid JSON`})}}if(f.type==='html'&&!/lang=/.test(f.code||''))state.console.push({t:'warn',m:`${f.name}: missing lang attribute`})});renderConsole()}
function renderConsole(){if(!state.console.length)captureConsole();U('uv-console').innerHTML=`<div class="console-tools"><button id="consoleRun">▶ Run diagnostics</button><button id="consoleClear">Clear</button><button data-filter="all" class="on">All</button><button data-filter="error">Errors</button><button data-filter="warn">Warnings</button></div><div id="consoleOutput" class="console-output"></div>`;const draw=filter=>{const list=filter==='all'?state.console:state.console.filter(x=>x.t===filter);U('consoleOutput').innerHTML=list.map(x=>`<div class="console-line ${x.t}"><b>${x.t==='error'?'✕':x.t==='warn'?'⚠':'✓'}</b><span>${safe(x.m)}</span></div>`).join('')||'<p>No messages.</p>'};draw('all');U('consoleRun').onclick=captureConsole;U('consoleClear').onclick=()=>{state.console=[];U('consoleOutput').innerHTML='<p>Console cleared.</p>'};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>draw(b.dataset.filter))}
function renderDevice(){if(!U('uv-device'))return;U('uv-device').innerHTML=`<div class="device-bar"><button data-device="desktop" class="on">Desktop</button><button data-device="tablet">Tablet</button><button data-device="mobile">Mobile</button><button data-device="landscape">Landscape</button><button id="rotateDevice">Rotate</button><button id="deviceRefresh">Refresh</button></div><div class="device-stage"><div id="deviceShell" class="device-shell"><iframe id="deviceFrame" title="Responsive preview" sandbox="allow-scripts allow-modals"></iframe></div></div>`;U('deviceFrame').srcdoc=buildPreview();document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-device]').forEach(x=>x.classList.remove('on'));b.classList.add('on');U('deviceShell').className='device-shell '+(b.dataset.device==='desktop'?'':b.dataset.device)});U('rotateDevice').onclick=()=>U('deviceShell').classList.toggle('landscape');U('deviceRefresh').onclick=()=>U('deviceFrame').srcdoc=buildPreview()}
function renderDiff(){const f=currentFile||state.left||files()[0];if(!f)return;const old=(f.original||'').split('\n'),now=(f.code||'').split('\n');const line=(s,c)=>`<div class="diff-line ${c}">${safe(s)||' '}</div>`;U('uv-diff').innerHTML=`<div class="ultra-actions"><select id="diffFile">${fileOptions(f)}</select><button id="diffAccept">Accept current</button><button id="diffDiscard">Discard changes</button></div><div class="diff-layout"><section><p class="eyebrow">Original</p><div class="diff-box">${old.map((x,i)=>line((i+1)+'  '+x,old[i]!==now[i]?'del':'')).join('')}</div></section><section><p class="eyebrow">Current</p><div class="diff-box">${now.map((x,i)=>line((i+1)+'  '+x,old[i]!==now[i]?'add':'')).join('')}</div></section></div>`;U('diffFile').onchange=e=>{currentFile=findPath(e.target.value);renderDiff()};U('diffAccept').onclick=()=>{f.original=f.code;delete changes[pathOf(f)];renderChanges();persist();renderDiff();toast('Baseline updated')};U('diffDiscard').onclick=()=>{f.code=f.original||f.code;delete changes[pathOf(f)];renderChanges();persist();renderDiff();toast('Changes discarded')}
}
function addCommit(message,count){state.commits.unshift({id:Date.now().toString(16).slice(-7),message,count,date:new Date().toLocaleString(),snapshot:snapshot()});state.commits=state.commits.slice(0,12);localStorage.setItem('fileverse-ultra-commits',JSON.stringify(state.commits));renderHistory()}
function renderHistory(){if(!state.commits.length)state.commits=[{id:'initial',message:'Initial FileVerse workspace',count:0,date:'Project start',snapshot:snapshot()}];U('uv-history').innerHTML=`<div class="ultra-actions"><button id="quickCommit">＋ Create snapshot commit</button></div><div class="history-grid">${state.commits.map((c,i)=>`<article class="commit-card"><span class="commit-dot"></span><div><h3>${safe(c.message)}</h3><p>${safe(c.id)} · ${safe(c.date)} · ${c.count} changes</p></div><button data-restore="${i}">Restore</button></article>`).join('')}</div>`;U('quickCommit').onclick=()=>{const msg=prompt('Commit message','Polish FileVerse workspace');if(msg)addCommit(msg,Object.keys(changes||{}).length)};document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const c=state.commits[+b.dataset.restore];if(!confirm('Restore '+c.message+'?'))return;ROOT=JSON.parse(c.snapshot);link(ROOT);current=ROOT;changes={};rebuildTree();openDir(ROOT);persist();renderAll();toast('Snapshot restored')})}
const templates={
 Blank:{desc:'Minimal HTML, CSS and JavaScript starter.',tree:[['index.html','html','<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8"><title>New Project</title><link rel="stylesheet" href="style.css"></head><body><main id="app"><h1>Hello FileVerse</h1></main><script src="script.js"><\/script></body></html>'],['style.css','css','body { font-family: system-ui; padding: 3rem; }'],['script.js','js','console.log("Ready");']]},
 Portfolio:{desc:'Hero, projects and contact portfolio.',tree:[['index.html','html','<!DOCTYPE html><html lang="en"><body><header><h1>Creative Portfolio</h1><p>Designer & developer</p></header><main><section id="projects"></section></main></body></html>'],['style.css','css','body{margin:0;background:#0b1020;color:white;font-family:system-ui}header{padding:8rem 10vw}'],['script.js','js','document.querySelector("#projects").innerHTML="<h2>Selected work</h2>";']]},
 Dashboard:{desc:'Responsive analytics dashboard starter.',tree:[['index.html','html','<!DOCTYPE html><html lang="en"><body><aside>Dashboard</aside><main><h1>Overview</h1><section class="cards"></section></main></body></html>'],['style.css','css','body{display:grid;grid-template-columns:240px 1fr;margin:0;font-family:system-ui}aside,main{padding:2rem}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}'],['script.js','js','console.log("Dashboard loaded");']]},
 Game:{desc:'Canvas game loop and score HUD.',tree:[['index.html','html','<!DOCTYPE html><html><body><div id="hud">Score: <b id="score">0</b></div><canvas id="game" width="800" height="450"></canvas><script src="script.js"><\/script></body></html>'],['style.css','css','body{margin:0;display:grid;place-items:center;min-height:100vh;background:#080914;color:white}canvas{max-width:95vw;background:#11182e}'],['script.js','js','const c=document.querySelector("#game"),x=c.getContext("2d");function loop(){x.clearRect(0,0,c.width,c.height);x.fillStyle="#53f4ff";x.fillRect(370,200,60,60);requestAnimationFrame(loop)}loop();']]},
 Challenge:{desc:'CodePen challenge-ready multi-file structure.',tree:[['index.html','html','<!DOCTYPE html><html lang="en"><body><main class="challenge"><p>CodePen Challenge</p><h1>Build something memorable.</h1></main></body></html>'],['style.css','css',':root{--accent:#53f4ff}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#080914;color:white;font-family:system-ui}.challenge{text-align:center}'],['script.js','js','console.log("Challenge ready");'],['README.md','md','# CodePen Challenge\n\nA multi-file CodePen 2.0 project.']]}}
function renderTemplates(){U('uv-templates').innerHTML=`<p class="subtitle">Start a fresh virtual project from a curated structure. Your current workspace is saved in Undo history first.</p><div class="template-grid">${Object.entries(templates).map(([n,t])=>`<article class="template-card"><h3>${n}</h3><p>${t.desc}</p><button data-template="${n}">Use template</button></article>`).join('')}</div>`;document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>loadTemplate(b.dataset.template))}
function loadTemplate(name){if(!confirm('Replace the virtual workspace with '+name+' template?'))return;pushUndo('Load '+name+' template');ROOT={name:'~',type:'dir',children:templates[name].tree.map(([n,t,c])=>({name:n,type:t,code:c,size:calcSize(c),mod:'now'}))};link(ROOT);files().forEach(f=>f.original=f.code);current=ROOT;tabs=[];pins=[];changes=Object.fromEntries(files().map(f=>[pathOf(f),'A']));rebuildTree();openDir(ROOT);persist();renderAll();toast(name+' template loaded')}
function auditProject(){const fs=files(),html=fs.filter(f=>f.type==='html').map(f=>f.code||'').join('\n'),css=fs.filter(f=>f.type==='css').map(f=>f.code||'').join('\n'),checks=[];checks.push({ok:/<html[^>]+lang=/.test(html),title:'Document language',tip:'Add lang="en" or lang="ro" to <html>.'});checks.push({ok:/<title>.+<\/title>/s.test(html),title:'Page title',tip:'Add a descriptive title.'});checks.push({ok:![...html.matchAll(/<img\b[^>]*>/g)].some(m=>!(/\balt=/.test(m[0]))),title:'Image alternatives',tip:'Add alt text to every image.'});checks.push({ok:![...html.matchAll(/<button\b[^>]*>/g)].some(m=>!(/aria-label=|>[^<]/.test(m[0]))),title:'Button labels',tip:'Give icon buttons an accessible name.'});checks.push({ok:/@media/.test(css),title:'Responsive CSS',tip:'Add at least one responsive media query.'});checks.push({ok:/prefers-reduced-motion/.test(css),title:'Reduced motion',tip:'Respect prefers-reduced-motion.'});checks.push({ok:!/<input\b(?![^>]*(aria-label|id=))/.test(html),title:'Form labels',tip:'Associate inputs with labels.'});const score=Math.round(checks.filter(x=>x.ok).length/checks.length*100);return{score,checks}}
function renderAudit(){const a=auditProject();U('uv-audit').innerHTML=`<div class="score-row"><div class="audit-score">${a.score}</div><div><h2>Accessibility score</h2><p>Static analysis of the virtual HTML and CSS files.</p></div></div><div class="audit-meter"><span style="width:${a.score}%"></span></div><div class="audit-grid" style="margin-top:16px">${a.checks.map(x=>`<article class="audit-card ${x.ok?'pass':'warn'}"><h3>${x.ok?'✓':'⚠'} ${x.title}</h3><p>${x.ok?'Check passed.':x.tip}</p></article>`).join('')}</div>`}
function aiReply(action){const f=currentFile||state.left||files()[0],code=f?.code||'';const replies={explain:`${f?.name||'This file'} is a ${f?.type?.toUpperCase()||'source'} file with ${code.split('\n').length} lines. It contributes to the project through ${f?.type==='html'?'structure and semantics':f?.type==='css'?'visual design and responsive layout':f?.type==='js'?'interaction and application logic':'project content'}.`,bugs:diagnoseFile(f),readme:`Suggested README sections: Overview, Features, File Structure, Usage, Accessibility, Deployment and Credits.`,structure:`Suggested structure: src/components, src/utils, styles/tokens.css, assets, data, tests and .github/workflows.`,comments:`Add comments only around non-obvious state changes, data transformations and public functions; avoid narrating simple syntax.`,refactor:`Extract repeated selectors and UI state into reusable helpers, isolate persistence, and group render functions by feature.`,variables:`Create design tokens for background, surface, edge, text, muted, accent, success, warning, radius and shadow.`};appendAI('user',action);setTimeout(()=>appendAI('assistant',replies[action]||'I can inspect the active file and suggest a focused improvement.'),250)}
function diagnoseFile(f){if(!f)return'Open a file first.';const issues=[];if(f.type==='js'){try{new Function(f.code||'')}catch(e){issues.push(e.message)}if((f.code||'').includes('innerHTML'))issues.push('Review innerHTML usage when content is user-controlled.')}if(f.type==='html'&&!/lang=/.test(f.code||''))issues.push('Missing language attribute.');if(f.type==='css'&&!/@media/.test(f.code||''))issues.push('No responsive breakpoint detected.');return issues.length?'Possible issues: '+issues.join(' '):'No obvious static issues found in the active file.'}
function renderAI(){U('uv-ai').innerHTML=`<div class="ai-shell"><aside class="ai-sidebar"><p class="eyebrow">Quick actions</p><div class="ai-chips"><button data-ai="explain">Explain file</button><button data-ai="bugs">Find bug</button><button data-ai="readme">Generate README plan</button><button data-ai="structure">Suggest structure</button><button data-ai="comments">Add comments plan</button><button data-ai="refactor">Refactor plan</button><button data-ai="variables">CSS variables</button></div><p class="kbd-hint">Demo assistant: deterministic, local and API-free.</p></aside><section class="ai-chat"><div id="aiMessages" class="ai-messages"><div class="ai-msg">Hello Laura! Open a file or choose a quick action.</div></div><div class="ai-compose"><input id="aiInput" placeholder="Ask about the current project..."><button id="aiSend">Send</button></div></section></div>`;document.querySelectorAll('[data-ai]').forEach(b=>b.onclick=()=>aiReply(b.dataset.ai));U('aiSend').onclick=()=>{const q=U('aiInput').value.trim();if(!q)return;appendAI('user',q);setTimeout(()=>appendAI('assistant',diagnoseFile(currentFile||state.left)),250);U('aiInput').value=''};U('aiInput').onkeydown=e=>{if(e.key==='Enter')U('aiSend').click()}}
function appendAI(role,text){const box=U('aiMessages');if(!box)return;const m=document.createElement('div');m.className='ai-msg '+(role==='user'?'user':'');m.textContent=text;box.append(m);box.scrollTop=box.scrollHeight}
async function exportZip(){if(!window.JSZip)return toast('ZIP library unavailable');const zip=new JSZip();function walk(n,p=''){(n.children||[]).forEach(c=>c.type==='dir'?walk(c,p+c.name+'/'):zip.file(p+c.name,c.code||''))}walk(ROOT);zip.file('fileverse-workspace.json',snapshot());const blob=await zip.generateAsync({type:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fileverse-project.zip';a.click();URL.revokeObjectURL(a.href);toast('ZIP exported')}
async function importProject(e){const file=e.target.files[0];if(!file)return;try{if(file.name.endsWith('.json')){const data=JSON.parse(await file.text());ROOT=data.root||data;link(ROOT)}else if(file.name.endsWith('.zip')&&window.JSZip){const z=await JSZip.loadAsync(file),children=[];for(const [name,item] of Object.entries(z.files)){if(item.dir||name==='fileverse-workspace.json')continue;children.push({name:name.split('/').pop(),type:(name.split('.').pop()||'md').toLowerCase(),code:await item.async('text')})}ROOT={name:'~',type:'dir',children};link(ROOT)}else throw Error('Unsupported file');files().forEach(f=>f.original=f.code);current=ROOT;changes=Object.fromEntries(files().map(f=>[pathOf(f),'A']));rebuildTree();openDir(ROOT);persist();renderAll();toast('Project imported')}catch(err){toast('Import failed: '+err.message)}finally{e.target.value=''}}
const tourSteps=[
 {el:'.sidebar',title:'Project tree',text:'Browse, search, pin, drag and manage every virtual file.'},
 {el:'.preview',title:'File workspace',text:'Switch grid/list views, open tabs and inspect project metadata.'},
 {el:'.drawer',title:'Editable source',text:'Open any file to edit, save, copy, reset or download its code.',open:()=>files()[0]&&openFile(files()[0])},
 {el:'#ultraPanel',title:'Ultra Studio',text:'Use split editing, diagnostics, responsive preview, diff, history, templates, audit and AI tools.'},
 {el:'.source-panel',title:'Source control',text:'Track added, modified and deleted files and create simulated commits.'},
 {el:'.terminal-panel',title:'Terminal and deploy',text:'Run playful development and GitHub Pages commands.'}
];
function startTour(){state.tour=0;U('tourOverlay').classList.add('show');showTour()}
function tourStep(delta){state.tour+=delta;if(state.tour<0)state.tour=0;if(state.tour>=tourSteps.length)return endTour();showTour()}
function showTour(){document.querySelectorAll('.tour-focus').forEach(x=>x.classList.remove('tour-focus'));const s=tourSteps[state.tour];s.open?.();setTimeout(()=>{const el=document.querySelector(s.el);if(!el)return tourStep(1);el.classList.add('tour-focus');el.scrollIntoView({behavior:'smooth',block:'center'});U('tourTitle').textContent=`${state.tour+1}/${tourSteps.length} · ${s.title}`;U('tourText').textContent=s.text;const r=el.getBoundingClientRect(),card=U('tourCard');card.style.top=Math.min(innerHeight-250,Math.max(16,r.bottom+12))+'px';card.style.left=Math.min(innerWidth-380,Math.max(16,r.left))+'px';U('tourPrev').disabled=state.tour===0;U('tourNext').textContent=state.tour===tourSteps.length-1?'Finish':'Next'},180)}
function endTour(){document.querySelectorAll('.tour-focus').forEach(x=>x.classList.remove('tour-focus'));U('tourOverlay').classList.remove('show');toast('Product tour complete')}
ready(inject);
})();