(()=>{
const VSTORE='fileverse-version-history-v1';
const releases=[
{v:'1.0',title:'Explorer Foundation',date:'July 2026',note:'File tree, grid/list navigation, source preview and search.',tags:['Explorer','Preview','Search']},
{v:'2.0',title:'Pro Mini IDE',date:'July 2026',note:'Editable files, live preview, drag and drop, Source Control and challenge missions.',tags:['Editor','Live preview','Git tools']},
{v:'3.0',title:'Ultra Studio',date:'July 2026',note:'Split view, diagnostics, device preview, diff, templates, audit and AI assistant.',tags:['Split view','Audit','AI Assistant']},
{v:'4.0',title:'Version History',date:'Current',note:'Release timeline, snapshots, comparison, restoration and history export.',tags:['Snapshots','Restore','Compare'],current:true}
];
let versions=[],selected=null,lastAutoHash='';
const el=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const wait=fn=>{try{if(typeof ROOT!=='undefined'&&ROOT&&typeof snapshot==='function'){window.ROOT=ROOT;fn();return}}catch{}setTimeout(()=>wait(fn),120)};
function load(){try{versions=JSON.parse(localStorage.getItem(VSTORE)||'[]')}catch{versions=[]}}
function save(){localStorage.setItem(VSTORE,JSON.stringify(versions.slice(0,25)))}
function projectStats(root){let fileCount=0,folderCount=0,lines=0;const walk=n=>(n.children||[]).forEach(c=>{if(c.type==='dir'){folderCount++;walk(c)}else{fileCount++;lines+=(c.code||'').split('\n').length}});walk(root);return{fileCount,folderCount,lines}}
function currentData(){return JSON.parse(snapshot())}
function hash(data){let h=2166136261,s=JSON.stringify(data);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
function inject(){const section=document.createElement('section');section.id='versionHistory';section.className='version-history';section.innerHTML=`<div class="version-head"><div><p class="eyebrow">Version History</p><h2>Every stage of FileVerse, preserved.</h2></div><span class="version-badge version-current">v4.0 active</span></div><div class="version-toolbar"><div><button id="createVersion" class="primary">＋ Save version</button> <button id="autoVersion">Auto-save: On</button> <button id="exportVersions">Export history</button></div><select id="versionSort"><option value="new">Newest first</option><option value="old">Oldest first</option></select></div><div id="versionStats" class="version-stats"></div><div class="version-layout"><div><p class="eyebrow">Release timeline</p><div id="releaseTimeline" class="release-timeline"></div></div><div><p class="eyebrow">Workspace snapshots</p><div id="snapshotList" class="snapshot-list"></div><div id="versionCompare" class="version-compare" hidden></div></div></div>`;
(document.getElementById('ultraPanel')||document.querySelector('.workspace')).after(section);bind();render();if(!versions.length)createVersion('Initial workspace','Automatic baseline created when Version History was enabled','initial');lastAutoHash=hash(currentData())}
function bind(){el('createVersion').onclick=()=>openCreate();el('exportVersions').onclick=exportHistory;el('versionSort').onchange=renderSnapshots;let auto=localStorage.getItem(VSTORE+'-auto')!=='off';updateAuto(auto);el('autoVersion').onclick=()=>{auto=!auto;localStorage.setItem(VSTORE+'-auto',auto?'on':'off');updateAuto(auto)};setInterval(()=>{if(auto)autoSnapshot()},30000);document.addEventListener('visibilitychange',()=>{if(document.hidden&&auto)autoSnapshot()})}
function updateAuto(on){el('autoVersion').textContent='Auto-save: '+(on?'On':'Off');el('autoVersion').dataset.on=on}
function openCreate(){if(typeof showModal==='function'){showModal('Save workspace version',`<label class="version-modal-label">Version name<input id="versionName" value="Workspace ${versions.length+1}"></label><label class="version-modal-label">Release notes<textarea id="versionNotes" placeholder="What changed in this version?"></textarea></label><button id="versionConfirm">Save version</button>`,()=>{el('versionConfirm').onclick=()=>{createVersion(el('versionName').value.trim()||'Workspace version',el('versionNotes').value.trim()||'Manual snapshot');hideModal()}})}else createVersion('Workspace '+(versions.length+1),'Manual snapshot')}
function createVersion(name,notes,kind='manual'){const data=currentData(),stats=projectStats(data),item={id:'v-'+Date.now(),name,notes,kind,date:new Date().toLocaleString(),timestamp:Date.now(),data,stats,hash:hash(data)};versions.unshift(item);selected=item.id;save();lastAutoHash=item.hash;render();if(typeof toast==='function')toast('Version saved: '+name)}
function autoSnapshot(){const data=currentData(),h=hash(data);if(h===lastAutoHash)return;createVersion('Auto snapshot',`Automatic snapshot · ${Object.keys(typeof changes==='object'?changes:{}).length} tracked changes`,'auto')}
function render(){renderReleases();renderSnapshots();renderStats()}
function renderReleases(){el('releaseTimeline').innerHTML=releases.map(r=>`<article class="release-card"><div class="version-card-head"><h3>${safe(r.title)}</h3><span class="version-badge ${r.current?'version-current':''}">v${r.v}</span></div><p>${safe(r.date)} · ${safe(r.note)}</p><div class="change-tags">${r.tags.map(t=>`<span>${safe(t)}</span>`).join('')}</div></article>`).join('')}
function renderStats(){const latest=versions[0],totalSize=new Blob([JSON.stringify(versions)]).size;el('versionStats').innerHTML=`<article><strong>${versions.length}</strong><span>Saved versions</span></article><article><strong>${latest?.stats.fileCount||0}</strong><span>Files in latest</span></article><article><strong>${latest?.stats.lines||0}</strong><span>Lines preserved</span></article><article><strong>${(totalSize/1024).toFixed(1)} KB</strong><span>Local history</span></article>`}
function renderSnapshots(){const list=[...versions];if(el('versionSort')?.value==='old')list.reverse();el('snapshotList').innerHTML=list.length?list.map(v=>`<article class="snapshot-card ${selected===v.id?'selected':''}" data-version="${v.id}"><div class="version-card-head"><div><h3>${safe(v.name)}</h3><p>${safe(v.date)} · ${v.kind==='auto'?'Automatic':'Manual'}</p></div><span class="version-badge">${v.stats.fileCount} files</span></div><p>${safe(v.notes)}</p><div class="change-tags"><span>${v.stats.folderCount} folders</span><span>${v.stats.lines} lines</span><span>#${v.hash}</span></div><div class="version-actions"><button data-preview="${v.id}">Compare</button><button data-restore-version="${v.id}">Restore</button><button data-download-version="${v.id}">Export</button><button data-delete-version="${v.id}">Delete</button></div></article>`).join(''):'<div class="version-empty">No workspace versions saved yet.</div>';
document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>compareVersion(b.dataset.preview));document.querySelectorAll('[data-restore-version]').forEach(b=>b.onclick=()=>restoreVersion(b.dataset.restoreVersion));document.querySelectorAll('[data-download-version]').forEach(b=>b.onclick=()=>downloadVersion(b.dataset.downloadVersion));document.querySelectorAll('[data-delete-version]').forEach(b=>b.onclick=()=>deleteVersion(b.dataset.deleteVersion))}
function compareVersion(id){selected=id;const v=versions.find(x=>x.id===id);if(!v)return;const now=projectStats(currentData()),box=el('versionCompare');box.hidden=false;box.innerHTML=`<h3>Compare with ${safe(v.name)}</h3><p>${safe(v.notes)}</p><div class="compare-grid"><article><strong>${now.fileCount-v.stats.fileCount>=0?'+':''}${now.fileCount-v.stats.fileCount}</strong><span>File difference</span></article><article><strong>${now.folderCount-v.stats.folderCount>=0?'+':''}${now.folderCount-v.stats.folderCount}</strong><span>Folder difference</span></article><article><strong>${now.lines-v.stats.lines>=0?'+':''}${now.lines-v.stats.lines}</strong><span>Line difference</span></article></div>`;renderSnapshots()}
function restoreVersion(id){const v=versions.find(x=>x.id===id);if(!v||!confirm('Restore '+v.name+'? Current workspace will be saved first.'))return;createVersion('Before restore','Safety snapshot created before restoring '+v.name,'safety');ROOT=JSON.parse(JSON.stringify(v.data));window.ROOT=ROOT;link(ROOT);current=ROOT;changes={};tabs=[];pins=[];rebuildTree();openDir(ROOT);persist();selected=id;render();if(typeof renderAll==='function')renderAll();if(typeof toast==='function')toast('Restored '+v.name)}
function downloadVersion(id){const v=versions.find(x=>x.id===id);if(!v)return;download({app:'FileVerse 2.0',version:v.name,notes:v.notes,created:v.date,project:v.data},`fileverse-${v.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.json`)}
function deleteVersion(id){const v=versions.find(x=>x.id===id);if(!v||!confirm('Delete version '+v.name+'?'))return;versions=versions.filter(x=>x.id!==id);if(selected===id)selected=null;save();render()}
function exportHistory(){download({app:'FileVerse 2.0',exported:new Date().toISOString(),releases,versions},'fileverse-version-history.json')}
function download(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
load();wait(inject);
})();